"""Unpack a published champion into a runnable miner directory.

Takes a leg from a results archive — either an unpacked `champion/` source tree (how the public
results repo publishes them) or a `workspace.bundle` checked out at `CHAMPION.sha`, so the
deployed code is provably the nominated code — copies `<agent_dir>/modeling.py` verbatim, and
generates the thin serving shell: `miner.py` (a `ChampionMiner` subclass), `entrypoint.sh`,
`PROVENANCE.md`. Champions are single-file by contract (modeling.py imports nothing outside
numpy/pandas/stdlib), so nothing else is copied; a champion carrying weights ships them alongside
and needs its own copy step.

Self-verifying: before anything is written, the champion is run through the LIVE validator
contract (`validate_responses`) on a synthetic context, once per nominated profile. A champion
that fails the gate is not unpacked.

  uv run python -m synth_lib.serving.unpack_champion --campaign <name> --leg <leg>
"""

from __future__ import annotations

import argparse
import shutil
import stat
import subprocess
import tempfile
from datetime import UTC, datetime
from pathlib import Path
from string import Template

import numpy as np
import pandas as pd
from synth.simulation_input import SimulationInput  # type: ignore[import-untyped]
from synth.validator import response_validation_v2  # type: ignore[import-untyped]

from synth_lib.benchmark.generate_predictions import load_simulate
from synth_lib.serving.serve import wrap_output
from synth_lib.benchmark.nomination import Champion, parse_champion

# (time_increment, time_length) per nominated profile — the two live formats.
PROFILE_SHAPES = {"low": (60, 3_600), "high": (300, 86_400)}

MINER_TEMPLATE = Template(
    '''"""$name: serves the $campaign/$leg champion on SN50.

Generated by synth_lib/serving/unpack_champion.py — provenance in PROVENANCE.md.
Run via entrypoint.sh, not directly.
"""

from __future__ import annotations

import logging
import time

from synth_lib.serving.champion_miner import ChampionMiner

from .modeling import simulate


class $class_name(ChampionMiner):
    simulate_fn = staticmethod(simulate)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s %(message)s")
    with $class_name() as miner:
        while True:
            miner.print_info()
            time.sleep(60)
'''
)

ENTRYPOINT_TEMPLATE = Template(
    """#!/usr/bin/env bash
# Launches the $name miner on Bittensor Subnet 50.
# Configurable via env vars. Defaults target mainnet finney.

set -euo pipefail

SCRIPT_DIR="$$(cd "$$(dirname "$${BASH_SOURCE[0]}")" && pwd)"

NETWORK="$${NETWORK:-finney}"
NETUID="$${NETUID:-50}"
COLDKEY_NAME="$${COLDKEY_NAME:-miner}"
HOTKEY_NAME="$${HOTKEY_NAME:-default}"
PORT="$${PORT:-8091}"
VALIDATOR_MIN_STAKE="$${VALIDATOR_MIN_STAKE:-65000}"

exec uv run python3.12 "$${SCRIPT_DIR}/miner.py" \\
    --subtensor.network "$$NETWORK" \\
    --netuid "$$NETUID" \\
    --logging.debug \\
    --wallet.name "$$COLDKEY_NAME" \\
    --wallet.hotkey "$$HOTKEY_NAME" \\
    --axon.port "$$PORT" \\
    --blacklist.force_validator_permit true \\
    --blacklist.validator_min_stake "$$VALIDATOR_MIN_STAKE"
"""
)

PROVENANCE_TEMPLATE = Template(
    """# $name — provenance

- Campaign: `$campaign`, leg `$leg`
- Champion sha: `$sha` (from `campaign_results/$campaign/$leg/CHAMPION`)
- Source: `modeling.py` copied verbatim from the champion's `$agent_dir/modeling.py` at that sha
- Profiles: $profiles
- Unpacked: $date
- Contract gate at unpack: PASSED (`validate_responses` == CORRECT per profile, synthetic context)

The champion's research report, journal and full nomination notes live in
`campaign_results/$campaign/$leg/`.
"""
)


def run(cmd: list[str], what: str) -> None:
    result = subprocess.run(cmd, capture_output=True)
    if result.returncode != 0:
        tail = (result.stdout + result.stderr).decode(errors="replace")[-2000:]
        raise RuntimeError(f"{what} failed (rc={result.returncode}):\n{tail}")


def contract_gate(modeling_path: Path, profiles: tuple[str, ...]) -> None:
    """Run the unpacked module through the LIVE validator contract, once per profile."""
    simulate = load_simulate(modeling_path)
    idx = pd.date_range("2026-01-01", periods=8 * 24 * 60, freq="1min", tz="UTC")
    rng = np.random.default_rng(7)
    series = pd.Series(100.0 * np.exp(np.cumsum(rng.normal(0, 1e-4, len(idx)))), index=idx, name="close")
    t = idx[-1]
    for profile in profiles:
        time_increment, time_length = PROFILE_SHAPES[profile]
        simulation_input = SimulationInput(
            asset="BTC",
            start_time=t.isoformat(),
            time_increment=time_increment,
            time_length=time_length,
            num_simulations=4,
        )
        raw = simulate(
            asset="BTC",
            start_time=t.isoformat(),
            time_increment=time_increment,
            time_length=time_length,
            num_simulations=4,
            context_prices=series,
        )
        wrapped = wrap_output(raw, t.to_pydatetime(), time_increment)
        verdict = response_validation_v2.validate_responses(wrapped, simulation_input, process_time_str="1.0")
        if verdict != "CORRECT":
            raise RuntimeError(f"contract gate failed for profile {profile}: {verdict}")


def champion_source(leg_dir: Path, champion: Champion, tmp: Path) -> Path:
    """Directory holding the champion's modeling.py: the published `champion/` tree if present,
    otherwise a clone of `workspace.bundle` checked out at CHAMPION.sha."""
    unpacked = leg_dir / "champion" / champion.agent_dir
    if (unpacked / "modeling.py").exists():
        return unpacked
    if (leg_dir / "champion" / "modeling.py").exists():  # published flat
        return leg_dir / "champion"
    bundle = leg_dir / "workspace.bundle"
    if not bundle.exists():
        raise FileNotFoundError(f"no champion source in {leg_dir}: expected champion/ or workspace.bundle")
    clone = tmp / "clone"
    run(["git", "clone", "-q", str(bundle), str(clone)], f"clone {bundle}")
    run(["git", "-C", str(clone), "checkout", "-q", champion.sha], f"checkout {champion.sha}")
    return clone / champion.agent_dir


def class_name_for(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_")) + "Miner"


def unpack(campaign: str, leg: str, name: str | None, results_dir: Path, dest_root: Path) -> Path:
    leg_dir = results_dir / campaign / leg
    champion: Champion = parse_champion(leg_dir / "CHAMPION")
    name = name or f"{campaign.replace('-', '_')}_{leg}"
    dest = dest_root / name
    if dest.exists():
        raise FileExistsError(f"{dest} already exists — remove it first if you mean to re-unpack")

    with tempfile.TemporaryDirectory(prefix="unpack-") as tmp:
        source = champion_source(leg_dir, champion, Path(tmp))
        contract_gate(source / "modeling.py", champion.profiles)  # gate BEFORE writing anything
        dest.mkdir(parents=True)
        shutil.copy(source / "modeling.py", dest / "modeling.py")

    substitutions = {
        "name": name,
        "class_name": class_name_for(name),
        "campaign": campaign,
        "leg": leg,
        "sha": champion.sha,
        "agent_dir": champion.agent_dir,
        "profiles": ", ".join(champion.profiles),
        "date": datetime.now(tz=UTC).date().isoformat(),
    }
    (dest / "__init__.py").write_text("")
    (dest / "miner.py").write_text(MINER_TEMPLATE.substitute(substitutions))
    entrypoint = dest / "entrypoint.sh"
    entrypoint.write_text(ENTRYPOINT_TEMPLATE.substitute(substitutions))
    entrypoint.chmod(entrypoint.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    (dest / "PROVENANCE.md").write_text(PROVENANCE_TEMPLATE.substitute(substitutions))
    return dest


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--campaign", required=True)
    ap.add_argument("--leg", required=True)
    ap.add_argument("--name", default=None, help="default: <campaign>_<leg> with dashes underscored")
    ap.add_argument("--results-dir", type=Path, default=Path("campaign_results"))
    ap.add_argument("--dest", type=Path, default=Path("champions"))
    args = ap.parse_args()
    dest = unpack(args.campaign, args.leg, args.name, args.results_dir, args.dest)
    print(f"unpacked -> {dest} (contract gate: CORRECT)")


if __name__ == "__main__":
    main()
